name: integration_test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  integration_test:
    name: integration_test
    strategy:
      matrix:
        zk-version: [3.5.8, 3.6.1]
        go-version: ['oldstable', 'stable']
    runs-on: ubuntu-latest
    steps:
      - name: Go ${{ matrix.go-version }} setup
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }} 

      - name: Setup Java 14
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 14

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test code
        run: make test ZK_VERSION=${{ matrix.zk-version }}

      - name: Upload code coverage
        # only upload one result from the matrix. 
        if: ${{ strategy.job-index == 0 }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          file: ./profile.cov
